"""
医学诊断任务的自定义 reward：结果奖励 + 过程奖励。

- 结果奖励（两种模式）：
  1. 包含判断（默认）：真实答案包含在模型输出中则给分。
  2. Judge 模式：使用 Qwen3-8B 等 LLM 作为 judge，判断模型诊断与真实诊断是否一致；
     在 task_info 中设置 judge_model_name（及可选 judge_base_url）即启用。
- 过程奖励：每次 ask_patient 得到回答后，计算新增上下文对「对正确答案的置信度」的影响；
  置信度升高给正奖励，降低给惩罚。需 env 在 task_info 中传入 process_turns。
"""
from __future__ import annotations

import json
import re
import logging
from typing import Any
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

from rllm.agents.agent import Action
from rllm.rewards.reward_fn import RewardFunction
from rllm.rewards.reward_types import RewardOutput

logger = logging.getLogger(__name__)


def _normalize(s: str) -> str:
    """归一化文本：小写、去标点、合并空白。"""
    if not s or not isinstance(s, str):
        return ""
    s = re.sub(r"[^\w\s]", " ", s.lower())
    return " ".join(s.split())


# 与 diagnosis_tool 约定一致：最终诊断从 "The final diagnosis is: \boxed{xxx}." 中提取 xxx
_FINAL_DIAGNOSIS_LINE_RE = re.compile(
    r"The\s+final\s+diagnosis\s+is\s*:\s*\\box(?:ed)?\{(.+?)\}\s*\.?\s*",
    re.IGNORECASE | re.DOTALL,
)
_BOXED_RE = re.compile(r"\\box(?:ed)?\{(.+?)\}")


def _extract_final_diagnosis(text: str) -> str:
    """从模型输出中抽取最终诊断：优先从 'The final diagnosis is: \\boxed{xxx}.' 中取 xxx，否则取任意 \\boxed{xxx} 内容。"""
    text = (text or "").strip()
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    text = " ".join(text.split())
    m = _FINAL_DIAGNOSIS_LINE_RE.search(text)
    if m:
        return m.group(1).strip()
    m = _BOXED_RE.search(text)
    if m:
        return m.group(1).strip()
    return text


# ---------------------------------------------------------------------------
# 结果奖励（Judge 模式）：调用 LLM 判断模型诊断与真实诊断是否一致
# ---------------------------------------------------------------------------

JUDGE_SYSTEM_PROMPT = """You are a medical expert judging whether two diagnoses are clinically consistent.

Given:
1. Reference diagnosis (ground truth from the clinical record)
2. Model's diagnosis (generated by a diagnostic model)

You must decide: Does the model's diagnosis mean the same as or is it clinically consistent with the reference diagnosis? Consider synonyms, equivalent medical terms, and clinically equivalent formulations.

Answer with exactly one word: YES or NO.
- YES: the model's diagnosis is consistent with or equivalent to the reference.
- NO: the model's diagnosis is different or inconsistent with the reference."""


def _call_judge_api(
    model_diagnosis: str,
    ground_truth: str,
    judge_model_name: str,
    judge_base_url: str,
    api_key: str = "None",
    timeout: float = 30.0,
) -> tuple[bool, str]:
    """
    调用 OpenAI 兼容的 chat API，让 judge 模型判断两者是否一致。
    Returns:
        (is_consistent, raw_response_text)
    """
    if not judge_model_name or not judge_base_url:
        return False, ""

    url = judge_base_url.rstrip("/")
    if "/v1" not in url:
        url = f"{url}/v1"
    url = f"{url}/chat/completions"

    user_content = (
        f"Reference diagnosis (ground truth):\n{ground_truth}\n\n"
        f"Model's diagnosis:\n{model_diagnosis}\n\n"
        "Are they clinically consistent? Answer with exactly one word: YES or NO."
    )
    payload = {
        "model": judge_model_name,
        "messages": [
            {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
        ],
        "max_tokens": 16,
        "temperature": 0.0,
    }
    body = json.dumps(payload).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if api_key and str(api_key).strip() not in ("", "None"):
        headers["Authorization"] = f"Bearer {api_key}"

    try:
        req = Request(url, data=body, headers=headers, method="POST")
        with urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except (URLError, HTTPError, json.JSONDecodeError, KeyError, TypeError) as e:
        logger.warning("Judge API call failed: %s", e)
        return False, str(e)

    try:
        text = (data.get("choices") or [{}])[0].get("message", {}).get("content", "") or ""
    except (IndexError, TypeError):
        text = ""
    text_upper = text.strip().upper()
    is_consistent = text_upper == "YES" or (
        text_upper.startswith("YES") and len(text_upper) <= 10
    )
    return is_consistent, text


def result_reward_judge(
    model_output: str,
    ground_truth: str,
    judge_model_name: str,
    judge_base_url: str,
    api_key: str = "None",
    *,
    reward_if_consistent: float = 1.0,
    reward_if_not_consistent: float = 0.0,
) -> tuple[float, dict[str, Any]]:
    """
    结果奖励（Judge 模式）：用 LLM 判断模型诊断与真实诊断是否一致。
    """
    metadata: dict[str, Any] = {"result_reward_type": "judge"}
    pred = _extract_final_diagnosis(model_output)
    gold = (ground_truth or "").strip()

    if not gold:
        metadata["result_reward_reason"] = "no_ground_truth"
        return 0.0, metadata

    is_consistent, raw_judge = _call_judge_api(
        pred, gold, judge_model_name, judge_base_url, api_key
    )

    metadata["judge_consistent"] = is_consistent
    metadata["judge_raw_response"] = raw_judge if raw_judge else ""
    metadata["model_output_excerpt"] = pred[:300] if pred else ""

    reward = reward_if_consistent if is_consistent else reward_if_not_consistent
    return reward, metadata


# ---------------------------------------------------------------------------
# 结果奖励（包含判断）：真实答案是否包含在模型输出中
# ---------------------------------------------------------------------------


def result_reward(
    model_output: str,
    ground_truth: str,
    *,
    reward_if_contain: float = 1.0,
    reward_if_not_contain: float = 0.0,
    normalize: bool = True,
) -> tuple[float, dict[str, Any]]:
    """
    结果奖励：若 ground_truth 包含在 model_output 中则给 reward_if_contain，否则 reward_if_not_contain。
    默认用归一化后的子串包含判断；若 ground_truth 为空则返回 0 与 metadata。

    Returns:
        (reward, metadata)
    """
    metadata: dict[str, Any] = {"result_reward_type": "containment"}
    pred = _extract_final_diagnosis(model_output)
    gold = (ground_truth or "").strip()

    if not gold:
        metadata["result_reward_reason"] = "no_ground_truth"
        return 0.0, metadata

    if normalize:
        pred_n = _normalize(pred)
        gold_n = _normalize(gold)
    else:
        pred_n, gold_n = pred, gold

    # 真实答案是否包含在模型输出中
    contained = gold_n in pred_n if gold_n else False
    if not contained and gold_n and pred_n:
        # 可选：按词切分，若 gold 的多数关键词出现在 pred 中也给部分分
        gold_tokens = set(gold_n.split())
        pred_tokens = set(pred_n.split())
        overlap = len(gold_tokens & pred_tokens) / len(gold_tokens) if gold_tokens else 0.0
        contained = overlap >= 0.5  # 超过一半关键词出现即视为包含
        metadata["keyword_overlap"] = overlap

    reward = reward_if_contain if contained else reward_if_not_contain
    metadata["ground_truth_contained"] = contained
    metadata["model_output_excerpt"] = pred[:300] if pred else ""
    return reward, metadata


# ---------------------------------------------------------------------------
# 过程奖励：每次 ask_patient 后，新增上下文对「对正确答案置信度」的影响
# ---------------------------------------------------------------------------


def _confidence_heuristic(context_text: str, ground_truth: str) -> float:
    """
    基于关键词重叠的置信度启发式：context_text 中与 ground_truth 相关的信息越多，分数越高。
    返回 [0, 1] 的分数。
    """
    if not ground_truth or not context_text:
        return 0.0
    cn = _normalize(context_text)
    gn = _normalize(ground_truth)
    if not gn:
        return 0.0
    gt_tokens = set(gn.split())
    ctx_tokens = set(cn.split())
    # 去掉过短的 token
    gt_tokens = {t for t in gt_tokens if len(t) > 1}
    ctx_tokens = {t for t in ctx_tokens if len(t) > 1}
    if not gt_tokens:
        return 0.0
    overlap = len(gt_tokens & ctx_tokens) / len(gt_tokens)
    return min(1.0, overlap)


def process_reward(
    process_turns: list[dict],
    ground_truth: str,
    *,
    reward_scale: float = 0.2,
    min_turn_reward: float = -0.1,
    max_turn_reward: float = 0.2,
) -> tuple[float, list[dict]]:
    """
    过程奖励：对每个 ask_patient 轮次，比较「加入本轮回答前后」的置信度变化。
    - 置信度升高 → 正奖励
    - 置信度降低 → 惩罚

    process_turns 每项需包含:
        - "dialogue_before": 本轮之前的对话摘要或全文（用于算「之前」置信度）
        - "question": 本轮问的问题
        - "answer": 患者本轮回答（用于算「之后」置信度：dialogue_before + answer）

    Returns:
        (total_process_reward, per_turn_metadata_list)
    """
    if not process_turns or not ground_truth:
        return 0.0, []

    total = 0.0
    per_turn: list[dict] = []

    for i, turn in enumerate(process_turns):
        dialogue_before = (turn.get("dialogue_before") or "").strip()
        answer = (turn.get("answer") or "").strip()
        question = (turn.get("question") or "").strip()

        conf_before = _confidence_heuristic(dialogue_before, ground_truth)
        context_after = f"{dialogue_before}\n{answer}".strip()
        conf_after = _confidence_heuristic(context_after, ground_truth)

        delta = conf_after - conf_before
        # 缩放到 [min_turn_reward, max_turn_reward]
        turn_reward = max(min_turn_reward, min(max_turn_reward, delta * reward_scale))

        total += turn_reward
        per_turn.append({
            "turn": i,
            "conf_before": conf_before,
            "conf_after": conf_after,
            "delta": delta,
            "turn_reward": turn_reward,
        })

    return total, per_turn


# ---------------------------------------------------------------------------
# 组合 reward：供 env 调用的 (task_info, action) -> RewardOutput
# ---------------------------------------------------------------------------


def med_diagnosis_reward(
    task_info: dict,
    action: str,
    *,
    result_weight: float = 1.0,
    process_weight: float = 0.5,
    result_reward_if_contain: float = 1.0,
    result_reward_if_not_contain: float = 0.0,
    process_reward_scale: float = 0.2,
    process_min_turn: float = -0.1,
    process_max_turn: float = 0.2,
) -> RewardOutput:
    """
    医学诊断 reward（结果 + 过程）。

    task_info 需包含:
        - ground_truth 或 Final_Result: 真实诊断结果
        - process_turns (可选): 每次 ask_patient 的列表，每项含 dialogue_before, question, answer

    action: 模型最终输出（如 finish 的 response 或最后一轮文本）。
    """
    if isinstance(action, Action):
        action = action.action
    if isinstance(action, list):
        # 若传入的是 raw_action (tool_calls list)，尝试抽出 finish 的 response
        for item in action:
            if isinstance(item, dict):
                fn = item.get("function") or {}
                if fn.get("name") == "finish":
                    args = fn.get("arguments")
                    if isinstance(args, dict):
                        action = str(args.get("response", ""))
                        break
                    if isinstance(args, str):
                        import json
                        try:
                            action = str(json.loads(args).get("response", ""))
                        except Exception:
                            action = args
                        break
        else:
            action = str(action)
    else:
        action = str(action or "")

    ground_truth = (
        task_info.get("ground_truth")
        or task_info.get("Final_Result")
        or (task_info.get("ehr") or {}).get("Final_Result")
        or ""
    )
    if isinstance(ground_truth, dict):
        ground_truth = str(ground_truth.get("text", ground_truth))
    ground_truth = str(ground_truth).strip()

    # 结果奖励：若指定了 judge_model_name 则用 Judge 模式，否则用包含判断
    judge_model_name = (task_info.get("judge_model_name") or "").strip()
    judge_base_url = (task_info.get("judge_base_url") or "").strip()
    judge_api_key = task_info.get("judge_api_key") or task_info.get("api_key") or "None"

    if judge_model_name and judge_base_url:
        res_reward, res_meta = result_reward_judge(
            action,
            ground_truth,
            judge_model_name=judge_model_name,
            judge_base_url=judge_base_url,
            api_key=judge_api_key,
            reward_if_consistent=result_reward_if_contain,
            reward_if_not_consistent=result_reward_if_not_contain,
        )
        is_correct = res_meta.get("judge_consistent", False)
    else:
        res_reward, res_meta = result_reward(
            action,
            ground_truth,
            reward_if_contain=result_reward_if_contain,
            reward_if_not_contain=result_reward_if_not_contain,
        )
        is_correct = res_meta.get("ground_truth_contained", False)

    # 过程奖励（仅当存在 process_turns 时计算）
    process_turns = task_info.get("process_turns") or []
    if process_turns and ground_truth:
        proc_reward, proc_meta = process_reward(
            process_turns,
            ground_truth,
            reward_scale=process_reward_scale,
            min_turn_reward=process_min_turn,
            max_turn_reward=process_max_turn,
        )
        total_reward = result_weight * res_reward + process_weight * proc_reward
        metadata = {**res_meta, "process_reward": proc_reward, "process_turn_details": proc_meta}
    else:
        total_reward = result_weight * res_reward
        metadata = res_meta

    metadata["result_reward"] = res_reward
    return RewardOutput(reward=total_reward, is_correct=is_correct, metadata=metadata)
